import QtQuick

QtObject {
    // Auto-generated by Noctalia's template engine — do NOT edit by hand.
    // Edit the source template instead:
    //   ~/.config/noctalia/templates/quickshell-colors.qml
    // and it will be re-rendered here every time your Noctalia colorscheme changes.
    //
    // NOTE: property names use the "m" prefix (mPrimary, mOnPrimary, ...) on
    // purpose — QML reserves any bare "onXxx" identifier as a signal-handler
    // slot, even for plain "property color onXxx: ..." declarations, so a
    // property literally named "onPrimary" fails to compile. This mirrors
    // Noctalia's own internal Color singleton naming for the same reason.

    readonly property color mPrimary: "#bec9c4"
    readonly property color mOnPrimary: "#28332f"
    readonly property color mSecondary: "#c4c7c5"
    readonly property color mOnSecondary: "#2d3130"
    readonly property color mTertiary: "#c6c5d1"
    readonly property color mOnTertiary: "#2e3039"
    readonly property color mError: "#ffb4ab"
    readonly property color mOnError: "#690005"

    readonly property color mSurface: "#131313"
    readonly property color mOnSurface: "#e4e2e1"
    readonly property color mSurfaceVariant: "#434846"
    readonly property color mOnSurfaceVariant: "#c3c8c5"

    readonly property color mOutline: "#8d928f"
    readonly property color mShadow: "#000000"

    // Helper: same color at a different opacity, e.g. colors.alpha(colors.mPrimary, 0.4)
    function alpha(c, a) {
        return Qt.rgba(c.r, c.g, c.b, a)
    }
}
