[colors.primary]
background = '#fbf9f7'
foreground = '#1b1c1b'

[colors.cursor]
text = '#fbf9f7'
cursor = '#1b1c1b'

[colors.vi_mode_cursor]
text = '#fbf9f7'
cursor = '#03110d'

[colors.search.matches]
foreground = '#dee4e0'
background = '#0c0e1a'

[colors.search.focused_match]
foreground = '#dee4e0'
background = '#03110d'

[colors.footer_bar]
foreground = '#dee4e0'
background = '#303030'

[colors.hints.start]
foreground = '#dee4e0'
background = '#59605d'

[colors.hints.end]
foreground = '#dee4e0'
background = '#59605d'

[colors.selection]
text = '#424845'
background = '#dee4e0'


[colors.normal]
black   = '#dee4e0'
red     = '#ba1a1a'
green   = '#03110d'
yellow  = '#59605d'
blue    = '#0c0e1a'
magenta = '#b8cbc3'
cyan    = '#c1c8c4'
white   = '#1b1c1b'


[colors.bright]
black   = '#737875'
red     = '#ba1a1a'
green   = '#03110d'
yellow  = '#59605d'
blue    = '#0c0e1a'
magenta = '#b8cbc3'
cyan    = '#c1c8c4'
white   = '#1b1c1b'


[colors.dim]
black   = '#dee4e0'
red     = '#ba1a1a'
green   = '#03110d'
yellow  = '#59605d'
blue    = '#0c0e1a'
magenta = '#b8cbc3'
cyan    = '#c1c8c4'
white   = '#1b1c1b'
