[colors.primary]
background = '#131313'
foreground = '#e4e2e1'

[colors.cursor]
text = '#131313'
cursor = '#e4e2e1'

[colors.vi_mode_cursor]
text = '#131313'
cursor = '#bec9c4'

[colors.search.matches]
foreground = '#434846'
background = '#c6c5d1'

[colors.search.focused_match]
foreground = '#434846'
background = '#bec9c4'

[colors.footer_bar]
foreground = '#434846'
background = '#e4e2e1'

[colors.hints.start]
foreground = '#434846'
background = '#c4c7c5'

[colors.hints.end]
foreground = '#434846'
background = '#c4c7c5'

[colors.selection]
text = '#c3c8c5'
background = '#434846'


[colors.normal]
black   = '#434846'
red     = '#ffb4ab'
green   = '#bec9c4'
yellow  = '#c4c7c5'
blue    = '#c6c5d1'
magenta = '#bec9c4'
cyan    = '#c4c7c5'
white   = '#e4e2e1'


[colors.bright]
black   = '#8d928f'
red     = '#ffb4ab'
green   = '#bec9c4'
yellow  = '#c4c7c5'
blue    = '#c6c5d1'
magenta = '#bec9c4'
cyan    = '#c4c7c5'
white   = '#e4e2e1'


[colors.dim]
black   = '#434846'
red     = '#ffb4ab'
green   = '#bec9c4'
yellow  = '#c4c7c5'
blue    = '#c6c5d1'
magenta = '#bec9c4'
cyan    = '#c4c7c5'
white   = '#e4e2e1'
